build:
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-fedora33"
  tags:
    - "x86_64-linux"
  script:
    - "cabal update && cabal build -f ci-build -w $GHC"
    - "HPC=hpc cabal test -w $GHC"
