resolver: lts-19.6
packages:
- '.'
allow-newer: true

build:
    haddock: true
    test: true
    test-arguments:
        additional-args: [--hide-successes]

extra-deps:
- process-1.6.13.2
- unix-2.7.2.2
- directory-1.3.7.0
- Cabal-3.6.2.0
- ghc-lib-parser-9.2.1.20211101
- git: https://github.com/AshleyYakeley/fourmolu.git
  commit: 3b62452795ac8029f7f645f834e74737a355bd14

ghc-options:
    "$locals": -Werror -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints -Wcompat -Wnoncanonical-monad-instances
