TOP = ../..
include $(TOP)/mk/boilerplate.mk

SRC_DEPS = binary bytestring array parallel primitive transformers mtl ghc-prim random

FAST_OPTS = 48
NORM_OPTS = 64
SLOW_OPTS = 256

ALL_DIRS += Random SamplerMonad Scene

include $(TOP)/mk/target.mk

