TOP = ../..
include $(TOP)/mk/boilerplate.mk

SRCS = BinConv.hs BinTest.hs Decode.hs Defaults.hs Encode.hs Main.hs PTTrees.hs Uncompress.hs

# Input files taken from http://mattmahoney.net/dc/enwik8.zip
#
include $(TOP)/mk/target.mk
