# Commit taken from https://gitlab.haskell.org/ghc/ci-images
variables:
  DOCKER_REV: 853f348f9caf38b08740b280296fbd34e09abb3a

.validate-hadrian:
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb10:$DOCKER_REV"
  tags:
    - x86_64-linux
  before_script:
    - git clean -xdf
    - $GHC --version
    - cabal --version
  script:
    - git submodule update --init --recursive
    - $GHC --version
    - cabal update
    - cabal new-run -w $GHC nofib-run -- -o out -w "$GHC" $EXTRA_ARGS
    - mkdir -p results
    - $GHC --info > results/compiler-info
    - cp _make/out/*.results.tsv results
  artifacts:
    paths:
      - results

validate-hadrian-normal:
  extends:
    - .validate-hadrian
  variables:
    EXTRA_ARGS: "--speed=Norm"

validate-hadrian-fast:
  extends:
    - .validate-hadrian
  variables:
    EXTRA_ARGS: "--speed=Fast"
