TOP = ../..
include $(TOP)/mk/boilerplate.mk

# This version just counts the results, and runs in constant space:
# PROG_ARGS += 7 1163

# This version builds a list of the results, and needs a lot of memory:
PROG_ARGS += 3 873

SRC_DEPS = parallel

include $(TOP)/mk/target.mk
