name: build
on:
  pull_request:
  push:
  schedule:
    - cron: 35 8 3 * *
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-latest, stack: lts-12.26, stack-extra-deps: "bytestring-0.11.3.0, filepath-1.4.100.0, unix-2.8.0.0" }
          - { os: macos-latest, stack: lts-19.21, stack-extra-deps: "bytestring-0.11.3.0, filepath-1.4.100.0, unix-2.8.0.0" }
          - { os: ubuntu-latest, ghc: 8.4.4, cabal: 3.0.0.0, overrides: "before_prepare() { sed -i.bak /utimensat/d configure.ac; }" }
          - { os: ubuntu-latest, ghc: 8.6.5, cabal: 3.0.0.0, overrides: "before_prepare() { sed -i.bak /utimensat/d configure.ac; }" }
          - { os: ubuntu-latest, ghc: 8.10.7, cabal: 3.8.1.0 }
          - { os: ubuntu-latest, ghc: 9.0.2, cabal: 3.8.1.0 }
          - { os: ubuntu-latest, ghc: 9.2.4, cabal: 3.8.1.0 }
          - { os: ubuntu-latest, ghc: 9.4.3, cabal: 3.8.1.0 }
          - { os: ubuntu-latest, ghc: latest, cabal: latest }
          - { os: windows-latest, stack: lts-12.26, stack-extra-deps: "bytestring-0.11.3.0, filepath-1.4.100.0, time-1.8.0.2, Win32-2.13.3.0", overrides: "before_prepare() { sed -i.bak -e /CreateSymbolicLinkW/d -e /GetFinalPathNameByHandleW/d configure.ac; }" }
          - { os: windows-latest, stack: lts-17.5, stack-extra-deps: "bytestring-0.11.3.0, filepath-1.4.100.0, time-1.9.3, Win32-2.13.3.0" }
          - { os: windows-latest, stack: lts-22.7, stack-extra-deps: "bytestring-0.11.5.3, filepath-1.4.100.0, time-1.12.2, Win32-2.14.0.0" }
    runs-on: ${{ matrix.os }}
    env:
      TESTSCRIPT_OVERRIDES: ${{ matrix.overrides }}
      STACK_EXTRA_DEPS: ${{ matrix.stack-extra-deps }}
      STACK_RESOLVER: ${{ matrix.stack }}
    steps:
      - if: startsWith(matrix.os, 'macos-')
        run: brew install automake
      - if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
      - if: startsWith(matrix.os, 'windows-')
        run: |
          echo STACK_FLAGS=--skip-msys >> $GITHUB_ENV
          echo 'C:\msys64\usr\bin' >> $GITHUB_PATH
      - if: startsWith(matrix.os, 'windows-')
        run: |
          pacman -S --needed --noconfirm autoconf automake
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: ${{ matrix.stack }}
          stack-no-global: ${{ matrix.stack }}
      - uses: actions/checkout@v3
      - run: tools/testscript prepare
      - run: tools/testscript build
      - if: matrix.cabal
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist-newstyle/sdist/*-*.tar.gz
