# -----------------------------------------------------------------------------
#
# (c) 2009 The University of Glasgow
#
# This file is part of the GHC build system.
#
# To understand how the build system works and how to modify it, see
#      http://ghc.haskell.org/trac/ghc/wiki/Building/Architecture
#      http://ghc.haskell.org/trac/ghc/wiki/Building/Modifying
#
# -----------------------------------------------------------------------------

TOP = ../..
include $(TOP)/mk/boilerplate.mk

PROG_ARGS += 400 400
SRC_DEPS = parallel

include $(TOP)/mk/target.mk
